package integration;

import car.domain.Car;
import integration.order.Order;

/**
 * Format-agnostic car report generator.
 * Creates content that can be rendered by any document format.
 */
public class CarReportGenerator {
    
    /**
     * Generates a plain text report for the car configuration.
     * This content is format-agnostic and can be used by any document type.
     * 
     * @param car the car to generate a report for
     * @return the report content
     */
    public String generateReport(Car car) {
        return generateReport(car, null);
    }

    public String generateReport(Car car, Order order) {
        StringBuilder sb = new StringBuilder();
        
        sb.append("VEHICLE SPECIFICATION REPORT\n");
        sb.append("============================\n\n");
        
        sb.append("Model: ").append(car.getModel().getDisplayName()).append("\n");
        sb.append("Color: ").append(car.getColor().getDisplayName()).append("\n\n");

        if (order != null) {
            sb.append("Order ID: ").append(order.getId()).append("\n");
            sb.append("Order Status: ").append(order.getStatus()).append("\n\n");
        }
        
        sb.append("POWERTRAIN\n");
        sb.append("----------\n");
        sb.append("Engine: ").append(car.getEngine()).append("\n");
        sb.append("Transmission: ").append(car.getTransmission()).append("\n\n");
        
        if (!car.getInteriorFeatures().isEmpty()) {
            sb.append("INTERIOR FEATURES\n");
            sb.append("-----------------\n");
            car.getInteriorFeatures().forEach(f -> 
                sb.append("- ").append(f.getDisplayName()).append("\n"));
            sb.append("\n");
        }
        
        if (!car.getExteriorFeatures().isEmpty()) {
            sb.append("EXTERIOR FEATURES\n");
            sb.append("-----------------\n");
            car.getExteriorFeatures().forEach(f -> 
                sb.append("- ").append(f.getDisplayName()).append("\n"));
            sb.append("\n");
        }
        
        if (!car.getSafetyFeatures().isEmpty()) {
            sb.append("SAFETY FEATURES\n");
            sb.append("---------------\n");
            car.getSafetyFeatures().forEach(f -> 
                sb.append("- ").append(f.getDisplayName()).append("\n"));
            sb.append("\n");
        }
        
        sb.append("============================\n");
        sb.append("Generated by Car Management System\n");
        
        return sb.toString();
    }
    
    /**
     * Generates a document title for the car report.
     * @param car the car
     * @return the document title
     */
    public String generateTitle(Car car) {
        return car.getModel().getDisplayName() + " - Configuration Report";
    }
}
